sudo: false
language: erlang
otp_release:
  - 20.3
  - 21.3
  - 22.0
script: rebar3 eunit -c
after_success:
  - pip install --user codecov
  - rebar3 covertool generate
  - mv _build/test/covertool/nautilus.covertool.xml cobertura.xml
  - codecov
